services:
  lightrag:
    container_name: lightrag
    image: ghcr.io/hkuds/lightrag:latest
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ghcr.io/hkuds/lightrag:latest
    ports:
      - "${PORT:-9621}:9621"
    volumes:
      - rag_storage:/app/data/rag_storage
      - inputs:/app/data/inputs
      - ./config.ini:/app/config.ini
      - ./.env:/app/.env
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - memgraph
    networks:
      - lightrag_network_lk_oldenburg
  memgraph:
    image: memgraph/memgraph:latest
    container_name: memgraph
    ports:
      - "7687:7687"
      - "7444:7444"
    volumes:
      - mg_lib_main:/var/lib/memgraph
      - mg_log_main:/var/log/memgraph
    command: ["--log-level=TRACE"]
    restart: unless-stopped
    networks:
      - lightrag_network_lk_oldenburg
volumes:
  rag_storage:
  inputs:
  mg_lib_main:
  mg_log_main:
  mg_etc_main:
networks:
  lightrag_network_lk_oldenburg:
    driver: bridge
